#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"


tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "____MENU OPENVPN E SSH RNEOX PREMIUM____" ; tput sgr0
echo ""
echo -e OBS: Digite - menu - para acessar o PACK RNEOX PREMIUM
echo -e "\033[0;32m| 0|• Muda porta do OPENVPN 443 e SSH 22\033[0;32m"
echo -e "| 1|\033[0;32m• Muda porta do SSH 443 e 22 E OPENVPN 8090\033[0m"
echo -e "| 2|\033[01;31m• UserCreate (Criar Usuarios SSH)\033[0m"
echo -e "| 3|\033[01;31m• UserBackup (Gerencia Backup dos Usuarios SSH)\033[0m"
echo -e "| 4|\033[01;31m• CpuMonitor (Monitora o Uso da CPU, RAM e UPTIME)\033[0m"
echo -e "| 5|\033[01;31m• UserMonitor (Monitora os Usuarios Conectados)\033[0m"
echo -e "| 6|\033[01;31m• DadosMonitor (Monitora o Uso de Dados/Banda|in||out|)\033[0m"
echo -e "| 7|\033[01;31m• VNC (Ativa a Interface Gráfica no Servidor)\033[0m"
echo -e "| 8|\033[01;31m• ClearCache (Limpa Cache e Swap da Maquina)\033[0m"
echo -e "| 9|\033[01;31m• OpenUDP (Libera Porta UDP p/ Ligacão e Jogos no HTTP)\033[0m"
echo -e "|10|\033[01;31m• SpeedTest (Testa a Velocidade de Link do Servidor)\033[0m"
echo -e "|11|\033[01;31m• Banner (Mensagem para Usuario Quando Conectar)\033[0m"
echo -e "|12|\033[01;31m• LimiterSSH (Limita as Conexoes de Cada Usuario)\033[0m"
echo -e "|13|\033[01;31m• MudarLimite (Muda o Limite do Usuario)\033[0m"
echo -e "|14|\033[01;31m• MudarSenha (Muda a Senha do Usuario)\033[0m"
echo -e "|15|\033[01;31m• MudarValidade (Muda a Data de Validade do Usuario)\033[0m"
echo -e "|16|\033[01;31m• DeletarUsuario (Deleta Usuario)\033[0m"
echo -e "|17|\033[01;31m• addhost (Adiciona Novo Host ao Squid)\033[0;32m"
echo -e "|18|\033[01;31m• OpenVPN Instalador (Só execute isso uma única vez)\033[01;36m"
echo -e "|19|\033[01;31m• LimparVencidos (Limpa Usuarios Vencidos)\033[0m"
echo -e "|20|\033[01;31m• KernelControl (Procura ATT para Kernel ou Remove)\033[0m"
echo -e "|21|\033[01;31m• SSHMonitor (Monitor Total de Usuarios Conectados)\033[0m"
echo -e "|22|\033[01;31m• VPNMonitor (Monitora os Usuarios Conectados no VPN)\033[0m"
echo -e Segure CTRL + C para fechar o menu
echo""
read -p " Selecione a opção [0-22]: " opcao

case $opcao in
 0)
  ConfVPN
  sleep 4
  menu;;
 1)
  ConfVPS
  sleep 4
  menu;;
 2)
  UserCreate
  sleep 5
  menu;;
 3)
  UserBackup
  sleep 5
  menu;;
 4)
  CpuMonitor;;
 5)
  UserMonitor;;
 6)
  DadosMonitor;;
 7)
  VNC
  sleep 8
  menu;;
 8)
  ClearCache
  sleep 4
  menu;;
 9)
  OpenUDP;;
 10)
  SpeedTest
  sleep 8
  menu;;
 11)
  Banner
  sleep 4
  menu;;
 12)
  LimiterSSH;;
 13)
  MudarLimite
  sleep 4
  menu;;
 14)
  MudarSenha
  sleep 4
  menu;;
 15)
  MudarValidade
  sleep 5
  menu;;
 16)
  UserDel
  sleep 4
  menu;;
 17)
  addhost
  sleep 4
  menu;;
 18)
  OpenVPN
  sleep 5
  menu;;
 19)
  UserClear
  sleep 3
  menu;;
 20)
  KernelControl
  sleep 2
  menu;;
 21)
  MonitorTotal.sh
  sleep 20
  menu;;
 22)
  statusvpn
  sleep 20
  menu;;
esac
