#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"

tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-10s\n' "____MENU OPENVPN E SSH RNEOX PREMIUM____" ; tput sgr0
echo ""
echo -e OBS: Digite - menu - para acessar o PACK RNEOX PREMIUM
echo -e "\033[0;32m| 0|• Mudar porta do OPENVPN 443 e SSH 22\033[0;32m"
echo -e "| 1|\033[0;32m• Mudar porta do SSH 443 e 22 E OPENVPN 8090\033[0m"
echo -e "| 2|\033[01;31m• UserCreate (Criar usuarios SSH)\033[0m"
echo -e "| 3|\033[01;31m• UserBackup (Gerencia backup dos usuarios SSH)\033[0m"
echo -e "| 4|\033[01;31m• CpuMonitor (Monitora o uso da CPU, RAM e UPTIME)\033[0m"
echo -e "| 5|\033[01;31m• UserMonitor (Monitora os usuarios conectados)\033[0m"
echo -e "| 6|\033[01;31m• DadosMonitor (Monitora o uso de dados/Banda|in||out|)\033[0m"
echo -e "| 7|\033[01;31m• VNC (Ativa a interface gráfica no servidor)\033[0m"
echo -e "| 8|\033[01;31m• ClearCache (Limpa cache e swap da maquina)\033[0m"
echo -e "| 9|\033[01;31m• OpenUDP (Libera porta UDP p/ ligacão e jogos no HTTP)\033[0m"
echo -e "|10|\033[01;31m• SpeedTest (Testa a velocidade de link do servidor)\033[0m"
echo -e "|11|\033[01;31m• Banner (Mensagem para usuario quando conectar)\033[0m"
echo -e "|12|\033[01;31m• LimiterSSH (Limita as conexoes SSH)\033[0m"
echo -e "|13|\033[01;31m• MudarLimite (Muda o limite dos usuario SSH)\033[0m"
echo -e "|14|\033[01;31m• MudarSenha (Muda a senha do usuario)\033[0m"
echo -e "|15|\033[01;31m• MudarValidade (Muda a data de validade do usuario)\033[0m"
echo -e "|16|\033[01;31m• DeletarUsuario (Deleta usuario)\033[0m"
echo -e "|17|\033[01;31m• addhost (Adiciona novo host ao squid)\033[0;32m"
echo -e "|18|\033[01;31m• OpenVPN Instalador (Só execute isso uma única vez)\033[01;36m"
echo -e "|19|\033[01;31m• LimparVencidos (Limpar usuarios vencidos)\033[0m"
echo -e "|20|\033[01;31m• KernelControl (Procurar update do Kernel ou Remove)\033[0m"
echo -e "|21|\033[01;31m• SSHMonitor (Monitorar o total de conectados no SSH)\033[0m"
echo -e "|22|\033[01;31m• VPNMonitor (Monitora os usuarios conectados no VPN)\033[0m"
echo -e "|23|\033[01;31m• Reboot (Reinicia o servidor)\033[0m"
echo -e "|24|\033[01;31m• ReiniciarServicos (SSH, VPN e ProxySquid)\033[0m"
echo -e Segure CTRL + C para fechar o menu
echo -e Escreva menudev para ver mais opções de administrador
echo""
read -p " Selecione a opção [0-24]: " opcao

case $opcao in
 0)
  ConfVPN
  sleep 1
  menu;;
 1)
  ConfVPS
  sleep 1
  menu;;
 2)
  UserCreate
  sleep 1
  menu;;
 3)
  UserBackup
  sleep 1
  menu;;
 4)
  CpuMonitor;;
 5)
  UserMonitor;;
 6)
  DadosMonitor;;
 7)
  VNC
  sleep 1
  menu;;
 8)
  ClearCache
  sleep 1
  menu;;
 9)
  OpenUDP;;
 10)
  SpeedTest
  sleep 5
  menu;;
 11)
  Banner
  sleep 2
  menu;;
 12)
  LimiterSSH;;
 13)
  MudarLimite
  sleep 1
  menu;;
 14)
  MudarSenha
  sleep 1
  menu;;
 15)
  MudarValidade
  sleep 1
  menu;;
 16)
  UserDel
  sleep 1
  menu;;
 17)
  addhost
  sleep 1
  menu;;
 18)
  OpenVPN
  sleep 1
  menu;;
 19)
  UserClear
  sleep 1
  menu;;
 20)
  KernelControl
  sleep 1
  menu;;
 21)
  MonitorTotal.sh
  sleep 7
  menu;;
 22)
  statusvpn
  sleep 7
  menu;;
 23)
 echo -e Reiniciando o servidor aguarde...
  reboot;;
 24)
  restservice
  sleep 1
  menu;;
esac
