#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"


tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "PackSSH" ; tput sgr0
echo ""
echo -e OBS:    Digite - PackSSH - para acessar esse PACK
echo -e "|01|\033[01;34m•====> ConfVPS (CONFIGURA A VPS|SQUID3|) \033[01;34m"
echo -e "|02|\033[01;31m•====> UserCreate (Criar Usuarios SSH)\033[0m"
echo -e "|03|\033[01;31m•====> UserBackup (Gerencia Backup dos Usuarios SSH)\033[0m"
echo -e "|04|\033[01;31m•====> CpuMonitor (Monitora o Uso da CPU, RAM e UPTIME)\033[0m"
echo -e "|05|\033[01;31m•====> UserMonitor (Monitora os Usuarios Conectados)\033[0m"
echo -e "|06|\033[01;31m•====> DadosMonitor (Monitora o Uso de Dados/Banda|in||out|)\033[0m"
echo -e "|07|\033[01;31m•====> VNC (Ativa a Interface Gráfica no Servidor)\033[0m"
echo -e "|08|\033[01;31m•====> ClearCache (Limpa Cache e Swap da Maquina)\033[0m"
echo -e "|09|\033[01;31m•====> OpenUDP (Libera a Porta UDP para Ligacão e Jogos)\033[0m"
echo -e "|10|\033[01;31m•====> SpeedTest (Testa a Velocidade de Link do Servidor)\033[0m"
echo -e "|11|\033[01;31m•====> Banner (Mensagem para Usuario Quando Conectar)\033[0m"
echo -e "|12|\033[01;31m•====> LimiterSSH (Limita as Conexoes de Cada Usuario)\033[0m"
echo -e "|13|\033[01;31m•====> MudarLimite (Muda o Limite do Usuario)\033[0m"
echo -e "|14|\033[01;31m•====> MudarSenha (Muda a Senha do Usuario)\033[0m"
echo -e "|15|\033[01;31m•====> MudarValidade (Muda a Data de Validade do Usuario)\033[0m"
echo -e "|16|\033[01;31m•====> UserDel (Deleta Usuario)\033[0m"
echo -e "|17|\033[01;31m•====> addhost (Adiciona Novo Host ao Squid)\033[0m"
echo -e "|18|\033[01;31m•====> OpenVPN (Configura e Gerencia Usuarios .ovpn)\033[0m"
echo -e "|19|\033[01;31m•====> UserClear (Limpa Usuarios Vencidos)\033[0m"
echo -e "|20|\033[01;31m•====> KernelControl (Procura ATT para Kernel ou Remove)\033[0m"
echo -e "|21|\033[01;31m•====> SSHMonitor (Monitor Total de Usuarios Conectados)\033[0m"
echo""
echo""
read -p " Selecione a opção [01-21]: " opcao

case $opcao in
 01)
  ConfVPS
  sleep 4
  PackSSH;;
 02)
  UserCreate
  sleep 5
  PackSSH;;
 03)
  UserBackup
  sleep 5
  PackSSH;;
 04)
  CpuMonitor;;
 05)
  UserMonitor;;
 06)
  DadosMonitor;;
 07)
  VNC
  sleep 8
  PackSSH;;
 08)
  ClearCache
  sleep 4
  PackSSH;;
 09)
  OpenUDP;;
 10)
  SpeedTest
  sleep 8
  PackSSH;;
 11)
  Banner
  sleep 4
  PackSSH;;
 12)
  LimiterSSH;;
 13)
  MudarLimite
  sleep 4
  PackSSH;;
 14)
  MudarSenha
  sleep 4
  PackSSH;;
 15)
  MudarValidade
  sleep 5
  PackSSH;;
 16)
  UserDel
  sleep 4
  PackSSH;;
 17)
  addhost
  sleep 4
  PackSSH;;
 18)
  OpenVPN
  sleep 5
  PackSSH;;
 19)
  UserClear
  sleep 3
  PackSSH;;
 20)
  KernelControl
  sleep 2
  PackSSH;;
 21)
  MonitorTotal.sh
  sleep 20
  PackSSH;;
esac
