#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"

echo -e "\033[1;30m (  _ \( \( )( ___)(  _  )( \/ )(  _ \  /__\   / __)( )/ ) \033[0m"
echo -e "\033[1;34m  )   / )  (  )__)  )(_)(  )  (  )___/ /(__)\ ( (__  )  (  \033[0m"
echo -e "\033[1;34m (_)\_)(_)\_)(____)(_____)(_/\_)(__)  (__)(__) \___)(_)\_) \033[0m"

sleep 5

tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "INSTALANDO PACKSSH" ; tput sgr0
echo -e "\033[1;34m INSTALANDO...\033[1;32m"

apt-get install bc 
apt-get install nano -y
apt-get install htop
apt-get install squid3 -y
sudo apt-get install screenfetch -y
rm .bashrc
rm screenfetch-dev
wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/.bashrc
wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/screenfetch-dev
clear
apt-get install python-pip -y
pip install speedtest-cli
apt-get install nethogs -y
apt-get install nload
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT

clear
wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/monitorcpu -O /bin/CpuMonitor
chmod +x /bin/CpuMonitor

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/LimpadorCache -O /bin/ClearCache
chmod +x /bin/ClearCache

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/usermonitor -O /bin/UserMonitor
chmod +x /bin/UserMonitor

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/OpenUdp -O /bin/OpenUDP
chmod +x /bin/OpenUDP

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/TesteConexao -O /bin/SpeedTest
chmod +x /bin/SpeedTest

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/Banner -O /bin/Banner
chmod +x /bin/Banner

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/UserBackup -O /bin/UserBackup
chmod +x /bin/UserBackup

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/UserCreate -O /bin/UserCreate
chmod +x /bin/UserCreate

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/UserClear -O /bin/UserClear
chmod +x /bin/UserClear

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/LimiterSSH -O /bin/LimiterSSH
chmod +x /bin/LimiterSSH

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/MonitorTotal -O /bin/MonitorTotal.sh
chmod +x /bin/MonitorTotal.sh

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/MudarLimite -O /bin/MudarLimite
chmod +x /bin/MudarLimite

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/MudarSenha -O /bin/MudarSenha
chmod +x /bin/MudarSenha

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/ConfVps -O /bin/ConfVPS
chmod +x /bin/ConfVPS

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/MudarValidade -O /bin/MudarValidade
chmod +x /bin/MudarValidade

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/VNC -O /bin/VNC
chmod +x /bin/VNC

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/UserDel -O /bin/UserDel
chmod +x /bin/UserDel

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/KernelControl -O /bin/KernelControl
chmod +x /bin/KernelControl

wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/DadosMonitor -O /bin/DadosMonitor
chmod +x /bin/DadosMonitor

wget https://raw.githubusercontent.com/dhtm15/script/master/ovinstall -O /bin/OpenVPN
chmod +x /bin/OpenVPN
 
wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/menu -O /bin/menu
chmod +x /bin/menu

rm -rf /etc/ssh/sshd_config
wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/sshd_config2 -O /etc/ssh/sshd_config
wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/squidconf
chmod +x squidconf
./squidconf
wget https://raw.githubusercontent.com/dhtm15/virustrojan/master/payloads -O /etc/payloads

/etc/init.d/ssh restart
service ssh restart

/etc/init.d/squid3 restart
service squid3 restart
service squid restart
clear




tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "menu" ; tput sgr0
echo ""
echo -e OBS:    Digite - menu - para acessar o PACK RNEOX PREMIUM
echo -e "|00|\033[01;34m•====> Instala OPENVPN 443 e SSH 22\033[01;34m"
echo -e "|01|\033[01;34m•====> Instala SSH 443 e 22 E OPENVPN 8090\033[01;34m"
echo -e "|02|\033[01;31m•====> UserCreate (Criar Usuarios SSH)\033[0m"
echo -e "|03|\033[01;31m•====> UserBackup (Gerencia Backup dos Usuarios SSH)\033[0m"
echo -e "|04|\033[01;31m•====> CpuMonitor (Monitora o Uso da CPU, RAM e UPTIME)\033[0m"
echo -e "|05|\033[01;31m•====> UserMonitor (Monitora os Usuarios Conectados)\033[0m"
echo -e "|06|\033[01;31m•====> DadosMonitor (Monitora o Uso de Dados/Banda|in||out|)\033[0m"
echo -e "|07|\033[01;31m•====> VNC (Ativa a Interface Gráfica no Servidor)\033[0m"
echo -e "|08|\033[01;31m•====> ClearCache (Limpa Cache e Swap da Maquina)\033[0m"
echo -e "|09|\033[01;31m•====> OpenUDP (Libera Porta UDP p/ Ligacão e Jogos no HTTP)\033[0m"
echo -e "|10|\033[01;31m•====> SpeedTest (Testa a Velocidade de Link do Servidor)\033[0m"
echo -e "|11|\033[01;31m•====> Banner (Mensagem para Usuario Quando Conectar)\033[0m"
echo -e "|12|\033[01;31m•====> LimiterSSH (Limita as Conexoes de Cada Usuario)\033[0m"
echo -e "|13|\033[01;31m•====> MudarLimite (Muda o Limite do Usuario)\033[0m"
echo -e "|14|\033[01;31m•====> MudarSenha (Muda a Senha do Usuario)\033[0m"
echo -e "|15|\033[01;31m•====> MudarValidade (Muda a Data de Validade do Usuario)\033[0m"
echo -e "|16|\033[01;31m•====> DeletarUsuario (Deleta Usuario)\033[0m"
echo -e "|17|\033[01;31m•====> addhost (Adiciona Novo Host ao Squid)\033[0m"
echo -e "|18|\033[01;31m•====> OpenVPN (Configura e Gerencia Usuarios .ovpn)\033[0m"
echo -e "|19|\033[01;31m•====> LimparVencidos (Limpa Usuarios Vencidos)\033[0m"
echo -e "|20|\033[01;31m•====> KernelControl (Procura ATT para Kernel ou Remove)\033[0m"
echo -e "|21|\033[01;31m•====> SSHMonitor (Monitor Total de Usuarios Conectados)\033[0m"
echo -e "|22|\033[01;31m•====> VPNMonitor (Monitora os Usuarios Conectados no VPN)\033[0m"
echo""
echo""
read -p " Selecione a opção [00-22]: " opcao

case $opcao in
 00)
  ConfVPN
  sleep 4
  menu;;
 01)
  ConfVPS
  sleep 4
  menu;;
 02)
  UserCreate
  sleep 5
  menu;;
 03)
  UserBackup
  sleep 5
  menu;;
 04)
  CpuMonitor;;
 05)
  UserMonitor;;
 06)
  DadosMonitor;;
 07)
  VNC
  sleep 8
  menu;;
 08)
  ClearCache
  sleep 4
  menu;;
 09)
  OpenUDP;;
 10)
  SpeedTest
  sleep 8
  menu;;
 11)
  Banner
  sleep 4
  menu;;
 12)
  LimiterSSH;;
 13)
  MudarLimite
  sleep 4
  menu;;
 14)
  MudarSenha
  sleep 4
  menu;;
 15)
  MudarValidade
  sleep 5
  menu;;
 16)
  UserDel
  sleep 4
  menu;;
 17)
  addhost
  sleep 4
  menu;;
 18)
  OpenVPN
  sleep 5
  menu;;
 19)
  UserClear
  sleep 3
  menu;;
 20)
  KernelControl
  sleep 2
  menu;;
 21)
  MonitorTotal.sh
  sleep 20
  menu;;
 22)
  statusvpn
  sleep 20
  menu;;
esac
