#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"




while true; do

echo -e "\033[0;32m*********************************************************\033[0;32m"
echo -e " \033[47;30m       ỮŞỮΔŘƗØŞ            |          ĆØŇ€ЖØ€Ş         \033[0m"
echo -e "\033[0;32m*********************************************************\033[0;32m"
        for usur in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi systemd-[a-z] |grep -vi systemd-[0-9]`; do
	usurnum=$(ps -u $usur |grep sshd |wc -l)
        echo -e "\033[1;33m    $(printf '%-42s%s' $usur $usurnum) \033[0m"
        echo -e "\033[0;32m*********************************************************\033[0;32m"
        done
sleep 6s
clear
done
